# Generated by Django 4.0.6 on 2022-07-31 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_id', models.CharField(default='', max_length=250, null=True)),
                ('Payment_id', models.CharField(default='', max_length=100, null=True)),
                ('Amount', models.BigIntegerField(default=0, null=True)),
                ('Currency', models.CharField(default='', max_length=20, null=True)),
                ('Status', models.CharField(default='', max_length=20, null=True)),
                ('Invoice_id', models.CharField(default='', max_length=100, null=True)),
                ('International', models.BooleanField(default=False, null=True)),
                ('Method', models.CharField(default='', max_length=30, null=True)),
                ('Amount_refunded', models.BigIntegerField(default=0, null=True)),
                ('Refund_Status', models.CharField(default='', max_length=30, null=True)),
                ('Card_id', models.CharField(default='', max_length=30, null=True)),
                ('Bank', models.CharField(default='', max_length=30, null=True)),
                ('Wallet', models.CharField(default='', max_length=30, null=True)),
                ('Upi_id', models.CharField(default='', max_length=30, null=True)),
                ('Email', models.CharField(default='', max_length=230, null=True)),
                ('Contact', models.CharField(default=0, max_length=32, null=True)),
                ('Upi_Transaction_id', models.CharField(default='', max_length=250, null=True)),
                ('Create_at', models.CharField(default='', max_length=50, null=True)),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
