# Generated by Django 4.0.6 on 2022-07-31 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_detail',
            name='Bank',
        ),
        migrations.RemoveField(
            model_name='payment_detail',
            name='Card_id',
        ),
        migrations.RemoveField(
            model_name='payment_detail',
            name='Invoice_id',
        ),
        migrations.RemoveField(
            model_name='payment_detail',
            name='Refund_Status',
        ),
        migrations.RemoveField(
            model_name='payment_detail',
            name='Wallet',
        ),
    ]
